{"uuid": "19fec990-aa48-4571-a6fd-f8a4ba007884", "children": ["9fc98290-d56c-4d0e-af98-53a5dfc35ac7", "47852cdc-af3d-4fc4-aead-74f07436c09f", "8c0bb5ad-4071-4196-9b8b-98652660d032"], "befores": [{"name": "beforeClass", "status": "broken", "statusDetails": {"message": "AttributeError: cls not available in session-scoped context\n", "trace": "  File \"C:\\Users\\ajinkyas.shukla_info\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Users\\ajinkyas.shukla_info\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Users\\ajinkyas.shukla_info\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"D:\\PracticeFramework\\SeleniumPracticeFramework\\test\\conftest.py\", line 16, in beforeClass\n    if request.cls is not None:\n  File \"C:\\Users\\ajinkyas.shukla_info\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 470, in cls\n    raise AttributeError(f\"cls not available in {self.scope}-scoped context\")\n"}, "start": 1658754149920, "stop": 1658754164184}], "start": 1658754149920, "stop": 1658754164219}