{"name": "test_enterDataInForm", "status": "failed", "statusDetails": {"message": "AssertionError", "trace": "self = <pages.navigateToUserRegistration.loginFile object at 0x0000018646FC67D0>\nlocatorvalue = 'SubmitCreate', locatortype = 'name'\n\n    def clickOnElement(self, locatorvalue, locatortype=\"xpath\"):\n        element = None\n        try:\n            locatortype = locatortype.lower()\n            element = self.get_element(locatorvalue, locatortype)\n>           element.click()\nE           AttributeError: 'NoneType' object has no attribute 'click'\n\n..\\base\\basefile.py:85: AttributeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <test.CreateAccounttest.CreateAccountTest testMethod=test_enterDataInForm>\n\n    @pytest.mark.run(order=2)\n    def test_enterDataInForm(self):\n        # self.sp.clickOnSignin()\n        # self.sp.verifyLoginFormloaded()\n        self.sp.enterEmailId()\n>       self.sp.submitButtonClick()\n\n..\\test\\CreateAccounttest.py:29: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\pages\\navigateToUserRegistration.py:43: in submitButtonClick\n    self.clickOnElement(self._clickCreateAccountbutton, \"name\")\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <pages.navigateToUserRegistration.loginFile object at 0x0000018646FC67D0>\nlocatorvalue = 'SubmitCreate', locatortype = 'name'\n\n    def clickOnElement(self, locatorvalue, locatortype=\"xpath\"):\n        element = None\n        try:\n            locatortype = locatortype.lower()\n            element = self.get_element(locatorvalue, locatortype)\n            element.click()\n            print(\"clicked on element with locatortype: \" + locatortype + \" and with the locatorvalue :\" + locatorvalue)\n        except:\n            print(\n                \"unable to click on element with locatortype: \" + locatortype + \" and with the locatorvalue :\" + locatorvalue)\n            self.take_screenshot(\"Screenshots\")\n>           assert False\nE           AssertionError\n\n..\\base\\basefile.py:91: AssertionError"}, "steps": [{"name": "*******Entered the Email id specified above************", "status": "passed", "start": 1658827892306, "stop": 1658827892306}], "attachments": [{"name": "Screenshots", "source": "a6261e85-ef14-4bc4-8a00-5d6f655d62ff-attachment.png", "type": "image/png"}, {"name": "stdout", "source": "ab3e9a03-fa47-4579-bee2-2640e690ae88-attachment.txt", "type": "text/plain"}], "start": 1658827892119, "stop": 1658827892565, "uuid": "30c4237f-3c9b-406a-bdf3-896f1ba20470", "historyId": "e1d7f5e0e0fb83f4216c733bc2a369e6", "testCaseId": "dba9f428dca54619458bb6ebffe2b28b", "fullName": "test.TestSuite.CreateAccountTest#test_enterDataInForm", "labels": [{"name": "tag", "value": "run(order=2)"}, {"name": "tag", "value": "@pytest.mark.usefixtures('beforeClass', 'beforeMethod')"}, {"name": "parentSuite", "value": "test"}, {"name": "suite", "value": "TestSuite"}, {"name": "subSuite", "value": "CreateAccountTest"}, {"name": "host", "value": "IB-SEZ-LAP-826"}, {"name": "thread", "value": "24428-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test.TestSuite"}]}